apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-gitops
spec:
  rules:
    - host: hello-gitops.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 8080